export const data = [
  {
    _id: "651a898547bb67384c52fa9d",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:12:37.149Z",
    updatedAt: "2023-10-02T09:12:37.149Z",
    __v: 0,
  },
  {
    _id: "651a899647bb67384c52fa9f",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:12:54.164Z",
    updatedAt: "2023-10-02T09:12:54.164Z",
    __v: 0,
  },
  {
    _id: "651a89ab47bb67384c52faa1",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:13:15.715Z",
    updatedAt: "2023-10-02T09:13:15.715Z",
    __v: 0,
  },
  {
    _id: "651a89c947bb67384c52faa3",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:13:45.103Z",
    updatedAt: "2023-10-02T09:13:45.103Z",
    __v: 0,
  },
  {
    _id: "651a8a1547bb67384c52faa6",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:15:01.283Z",
    updatedAt: "2023-10-02T09:15:01.283Z",
    __v: 0,
  },
  {
    _id: "651a8ba047bb67384c52faaa",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:21:36.980Z",
    updatedAt: "2023-10-02T09:21:36.980Z",
    __v: 0,
  },
  {
    _id: "651a8bc447bb67384c52faac",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:22:12.786Z",
    updatedAt: "2023-10-02T09:22:12.786Z",
    __v: 0,
  },
  {
    _id: "651a8d1147bb67384c52fab2",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:27:45.917Z",
    updatedAt: "2023-10-02T09:27:45.917Z",
    __v: 0,
  },
  {
    _id: "651a8d5847bb67384c52fab4",
    imagePath: "https://picsum.photos/seed/I5Xmd/640/480",
    name: "Paket Adı 9",
    details: ["Soft", "Small", "Sleek"],
    tags: ["Shoes", "Rustic", "Sleek"],
    amount: 24,
    currency: "₺",
    moreInformation:
      "Placeat illo tenetur reiciendis mollitia a eligendi. Eius quam alias veniam consequatur asperiores. Autem molestias accusamus possimus libero sunt necessitatibus impedit itaque. Reiciendis quae neque quae nobis unde incidunt perferendis. Praesentium totam quis magni ab corporis. Fugit magni eligendi aut corporis in libero. Reiciendis reiciendis omnis nihil nostrum soluta minus repellendus. Harum ipsam atque necessitatibus iusto.",
    price: 436,
    createdAt: "2023-10-02T09:28:56.082Z",
    updatedAt: "2023-10-02T09:28:56.082Z",
    __v: 0,
  },
  {
    _id: "651a8d9f47bb67384c52fab7",
    imagePath: "https://picsum.photos/seed/OMFynPVzk2/640/480",
    name: "Paket Adı 6",
    details: ["Fresh", "Ergonomic", "Generic"],
    tags: ["Tools", "Refined", "Bespoke"],
    amount: 199,
    currency: "₺",
    moreInformation:
      "Odio labore mollitia ratione aperiam possimus accusamus. Magni veritatis est ratione commodi laboriosam suscipit. Ullam explicabo repellendus. Quas inventore assumenda impedit perferendis. Repellat consequatur recusandae velit necessitatibus tenetur iste nemo. Optio voluptatibus minus aperiam. Iste reiciendis vero blanditiis blanditiis aliquid sit ex. Dolore deserunt asperiores repudiandae maxime at saepe atque. Nisi dolores nesciunt libero quia id ipsam corrupti. Labore magni cum nisi voluptate.",
    price: 782,
    createdAt: "2023-10-02T09:30:07.167Z",
    updatedAt: "2023-10-02T09:30:07.167Z",
    __v: 0,
  },
  {
    _id: "656848e994665375f74a0e0d",
    imagePath: "https://picsum.photos/seed/bayclpF4I6/640/480",
    name: "Random Package Name 5",
    details: ["Fresh", "Unbranded", "Rustic"],
    tags: ["Electronics", "Luxurious", "Luxurious"],
    amount: 48,
    currency: "₺",
    moreInformation:
      "Minima temporibus hic error fugit. Nobis perspiciatis omnis quos saepe. Praesentium magni officiis voluptatum iste eaque nobis saepe eius. Aspernatur voluptatum id facilis cum explicabo voluptatibus voluptatum nesciunt.",
    price: 349,
    createdAt: "2023-11-30T08:33:45.203Z",
    updatedAt: "2023-11-30T08:33:45.203Z",
    __v: 0,
  },
  {
    _id: "65f280f520d70d50ba775b48",
    imagePath: "https://picsum.photos/seed/uetIYGB7k/640/480",
    name: "Random Package Name 5",
    details: ["Cotton", "Awesome", "Rustic"],
    tags: ["Computers", "Gorgeous", "Electronic"],
    amount: 180,
    currency: "₺",
    moreInformation:
      "Reiciendis repudiandae incidunt quam. Dolores unde harum vitae ad molestiae ratione facilis. Voluptas tenetur reprehenderit sunt eum. Itaque commodi recusandae totam.",
    price: 678,
    createdAt: "2024-03-14T04:45:41.768Z",
    updatedAt: "2024-03-14T04:45:41.768Z",
    __v: 0,
  },
  {
    _id: "65f280f820d70d50ba775b4a",
    imagePath: "https://picsum.photos/seed/CN3QY6/640/480",
    name: "Random Package Name 8",
    details: ["Plastic", "Modern", "Small"],
    tags: ["Garden", "Elegant", "Intelligent"],
    amount: 170,
    currency: "₺",
    moreInformation:
      "Voluptates eos culpa. Expedita optio nostrum doloribus. Ex cupiditate fuga placeat. Perferendis aspernatur necessitatibus aut incidunt dolorum quis id.",
    price: 910,
    createdAt: "2024-03-14T04:45:44.121Z",
    updatedAt: "2024-03-14T04:45:44.121Z",
    __v: 0,
  },
  {
    _id: "65f280f920d70d50ba775b4c",
    imagePath: "https://picsum.photos/seed/DJTpgjVQZ/640/480",
    name: "Random Package Name 7",
    details: ["Rubber", "Ergonomic", "Tasty"],
    tags: ["Grocery", "Practical", "Licensed"],
    amount: 73,
    currency: "₺",
    moreInformation:
      "Vel perspiciatis aliquam. Ducimus praesentium at sit magnam nesciunt veritatis adipisci veniam. Magni est nisi inventore quod illum eum possimus quidem quis. Vel quia harum expedita.",
    price: 901,
    createdAt: "2024-03-14T04:45:45.820Z",
    updatedAt: "2024-03-14T04:45:45.820Z",
    __v: 0,
  },
  {
    _id: "65f280fa20d70d50ba775b4e",
    imagePath: "https://picsum.photos/seed/9AKHCg0mFI/640/480",
    name: "Random Package Name 4",
    details: ["Concrete", "Gorgeous", "Incredible"],
    tags: ["Movies", "Licensed", "Handcrafted"],
    amount: 138,
    currency: "₺",
    moreInformation:
      "Debitis natus ullam aut voluptas maxime hic. Aspernatur laborum omnis unde cupiditate similique rem expedita. Culpa aliquam maiores saepe a aperiam aliquid fugit accusantium. Cum error quidem quas veniam laudantium distinctio dicta accusantium distinctio.",
    price: 784,
    createdAt: "2024-03-14T04:45:46.881Z",
    updatedAt: "2024-03-14T04:45:46.881Z",
    __v: 0,
  },
  {
    _id: "65f280fb20d70d50ba775b50",
    imagePath: "https://picsum.photos/seed/p7FGmA2/640/480",
    name: "Random Package Name 8",
    details: ["Rubber", "Intelligent", "Fantastic"],
    tags: ["Toys", "Oriental", "Small"],
    amount: 187,
    currency: "₺",
    moreInformation:
      "Ea rem dolorum. Mollitia saepe suscipit nam cumque rem possimus ab. Hic reprehenderit voluptatum iusto nobis dolores consequuntur exercitationem quis. Ipsam vel voluptatibus incidunt asperiores voluptate iure sed nesciunt in. Fuga harum sequi soluta veritatis dolorem omnis adipisci tempora. Quos omnis temporibus debitis id totam amet. Cum voluptatum amet explicabo commodi delectus inventore. Quibusdam repellendus blanditiis quis quidem. Similique ratione sapiente aspernatur.",
    price: 111,
    createdAt: "2024-03-14T04:45:47.590Z",
    updatedAt: "2024-03-14T04:45:47.590Z",
    __v: 0,
  },
  {
    _id: "65ffeb12e45eefe8ba1d90cc",
    imagePath: "https://picsum.photos/seed/IVqmL/640/480",
    name: "Random Package Name 8",
    details: ["Plastic", "Handmade", "Refined"],
    tags: ["Sports", "Intelligent", "Fantastic"],
    amount: 134,
    currency: "₺",
    moreInformation:
      "Commodi dolore eos. Nemo maxime molestias quis laboriosam minus itaque. Sit omnis deleniti sint inventore veritatis eligendi iusto nam voluptates. Ex laborum saepe quasi recusandae dolores facere fuga cupiditate totam. Architecto expedita quae nesciunt iure. Unde dolor culpa.",
    price: 800,
    createdAt: "2024-03-24T08:57:54.291Z",
    updatedAt: "2024-03-24T08:57:54.291Z",
    __v: 0,
  },
  {
    _id: "65ffeb13e45eefe8ba1d90ce",
    imagePath: "https://picsum.photos/seed/iKjHxBAe/640/480",
    name: "Random Package Name 2",
    details: ["Rubber", "Modern", "Licensed"],
    tags: ["Automotive", "Handcrafted", "Intelligent"],
    amount: 161,
    currency: "₺",
    moreInformation:
      "Asperiores ipsam iste rem. Fugit corporis veniam atque et rerum. Neque eaque accusantium quis. Nesciunt ipsam asperiores laudantium cupiditate eligendi nisi reprehenderit.",
    price: 429,
    createdAt: "2024-03-24T08:57:55.958Z",
    updatedAt: "2024-03-24T08:57:55.958Z",
    __v: 0,
  },
  {
    _id: "663e14152493e0e81b3f4ad3",
    imagePath: "https://picsum.photos/seed/MSDCJxc/640/480",
    name: "Random Package Name 5",
    details: ["Bronze", "Generic", "Sleek"],
    tags: ["Computers", "Fantastic", "Elegant"],
    amount: 178,
    currency: "₺",
    moreInformation:
      "Sit saepe eveniet. Tempora non veniam voluptates. Rerum eligendi distinctio quisquam animi. Debitis tempora ea. Inventore nulla sunt aut voluptatum repudiandae fuga. Tenetur nesciunt non nesciunt. Expedita est aliquam. Numquam asperiores tempore expedita ad enim nulla repellendus eaque. Consequatur voluptates suscipit dolores ipsum.",
    price: 820,
    createdAt: "2024-05-10T12:33:25.286Z",
    updatedAt: "2024-05-10T12:33:25.286Z",
    __v: 0,
  },
];
